jobs:
  include:
    - language: shell
      os: linux
      dist: focal
      addons:
        apt:
          sources:
            - sourceline: deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
      arch: arm64
      services:
        - docker
      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        - sudo apt-get update
        - sudo apt-get remove docker docker.io containerd runc
        - sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce docker-ce-cli containerd.io
        - sudo service docker restart
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull debian:10
        - docker pull amazoncorretto:11
      install:
        - travis_wait bash ./clone-projector-core.sh
        - travis_wait bash ./build-container-aarch64.sh
        - docker images
        - docker tag projector-idea-c wdslb/projector-idea-c-arm64v8
        - docker push wdslb/projector-idea-c-arm64v8
        - docker rmi wdslb/projector-idea-c-arm64v8 -f
        - docker rmi projector-idea-c -f
    - language: shell
      os: linux
      dist: focal
      addons:
        apt:
          sources:
            - sourceline: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
      arch: amd64
      services:
        - docker
      before_install:
        - sudo apt-get update
        - sudo apt-get remove docker docker.io containerd runc
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce docker-ce-cli containerd.io
        - sudo service docker restart
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull debian:10
        - docker pull amazoncorretto:11
      install:
        - travis_wait bash ./clone-projector-core.sh
        - travis_wait bash ./build-container.sh
        - docker images
        - docker tag projector-idea-c wdslb/projector-idea-c-amd64
        - docker push wdslb/projector-idea-c-amd64
        - docker rmi wdslb/projector-idea-c-amd64 -f
        - docker rmi projector-idea-c -f

