language: bash

os: linux
dist: bionic

services:
  - docker

before_install:
  - sudo apt-get remove docker docker-engine docker.io containerd runc
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

install:
  - ./clone-projector-core.sh
  - ./build-container.sh
  - docker images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker tag projector-idea-c wdslb/projector-idea-c
  - docker push wdslb/projector-idea-c