jobs:
  include:
    - language: shell
      os: linux
      dist: focal
      arch: amd64
      services:
        - docker
      before_install:
        - sudo apt-get remove docker docker-engine docker.io containerd runc
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce docker-ce-cli containerd.io
        - sudo cat /etc/docker/daemon.json
        - sudo cat /etc/default/docker
        - sudo service docker restart
        - docker system info
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull debian:10
        - docker pull amazoncorretto:11
      install:
        - ./clone-projector-core.sh
        - ./build-container.sh
        - docker images
        - docker tag projector-idea-c wdslb/projector-idea-c
        - docker push wdslb/projector-idea-c
        - docker rmi wdslb/projector-idea-c -f
        - docker rmi projector-idea-c -f
    - language: shell
      os: linux
      dist: focal
      arch: arm64
      services:
        - docker
      before_install:
        - sudo apt-get update
        - sudo apt-get remove docker docker-engine docker.io containerd runc
        - sudo apt-get install apt-transport-https ca-certificates curl gnupg lsb-release
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        - echo "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce docker-ce-cli containerd.io
        - sudo cat /etc/docker/daemon.json
        - sudo cat /etc/default/docker
        - sudo service docker restart
        - docker system info
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker pull debian:10
        - docker pull amazoncorretto:11
      install:
        - ./clone-projector-core.sh
        - ./build-container-aarch64.sh
        - docker images
        - docker tag projector-idea-c wdslb/projector-idea-c
        - docker push wdslb/projector-idea-c
        - docker rmi wdslb/projector-idea-c -f
        - docker rmi projector-idea-c -f
