# Ignore everything but specific dirs

**

!/projector-client/**
!/projector-server/**
!/projector-docker/static/**
!/projector-docker/build_tools/**
!/projector-docker/idea_plugins/**
!/projector-docker/jce_policy/**
